apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tekton-images

resources:
- namespace.yaml
- rolebinding.yaml  # allow system:authenticated to pull images from this namespace!

# add image subdirectories here
- tekton-tools